### ISSUE TITLE
Dockerimage 

### ISSUE THREAD

**Issue by byustudent** [BenevolentAI/DeeplyTough#13]
Can you make the Dockerimage available for download? The computing cluster at my University does not permit the program Docker on our computer. Instead, we have udocker. So I can run a docker image, but I can't build the docker image from the docker file that you have available

**Comment by JoshuaMeyers** [comment]
Hey @byustudent thanks for your interest in deeplytough, I have pushed an image to my dockerhub which is provided as is.
https://hub.docker.com/r/joshuameyers/deeplytough
