### ISSUE TITLE
datasets_downloader.sh

### ISSUE THREAD

**Issue by C0921** [BenevolentAI/DeeplyTough#18]
Hi,
  I ran into a tricky problem. When I run the command datasets_downloader.sh, it cannot download the full data. I hope someone can help me with this problem.

**Comment by JoshuaMeyers** [comment]
Hi @C0921, thanks for your interest in DeeplyTough, could you post the output you get when running the script? Cheers, J.

**Comment by JoshuaMeyers** [comment]
Hey @C0921, apologies for the slow reply. The ProSPECCTs dataset had moved, I have updated the url. Can you confirm this now works for you? Thanks for highlighting the issue.

Fix is here https://github.com/BenevolentAI/DeeplyTough/commit/7536c5bb7d4e1e7e5d4f6cfacd1a437db03596e9
