### ISSUE TITLE
custom_evaluation.py stops during pre-processing

### ISSUE THREAD

**Issue by poelmans-robin** [BenevolentAI/DeeplyTough#28]
While running the custom_evaluation.py script I consistently run into the same problem. It seems that after pre-processing one file, the program stops for an unknown reason. As a workaround I can keep running "fg %1" over and over until every file is pre-processed, but suffice to say that this is not very efficient for larger datasets. You can find the output log for one of my runs below.

python $DEEPLYTOUGH/deeplytough/scripts/custom_evaluation.py --output_dir $DEEPLYTOUGH/results --device 'cuda:0' --nworkers 8 --net $DEEPLYTOUGH/networks/deeplytough_toughm1_test.pth.tar
HTMD: Logging setup failed
INFO:misc.utils:Pre-processing /home/biomol/Documents/databases/Biolip2/biolip2_opt/1px2/1px2_ATP_A_800/combined_1px2_ATP_A_800.pdb with HTMD...
adding gasteiger charges to peptide
INFO:misc.utils:Pre-processing /home/biomol/Documents/databases/PdbBind_opt/pdbbind_opt_sm/6p1l/6p1l_9LL_C_1103/combined_6p1l_9LL_C_1103.pdb with HTMD...

[1]+  Stopped                 python $DEEPLYTOUGH/deeplytough/scripts/custom_evaluation.py --output_dir $DEEPLYTOUGH/results --device 'cuda:0' --nworkers 8 --net $DEEPLYTOUGH/networks/deeplytough_toughm1_test.pth.tar

I run into the same problem on two different desktops, so I don't think the problem is hardware-related... I hope you can help. Thanks in advance for a reply.

Kind regards,
Robin

**Comment by JoshuaMeyers** [comment]
Hi Robin, the code is pretty fragile and is unsupported these days (especially as it decays over time) but this does sounds like a memory error, the command is expecting a GPU, do you have one on your desktops? if not change to `--device cpu`. Additionally you might consider reducing the number of workers `--nworkers 1`. It will be slow in this format though so you really want to have a GPU.

**Comment by poelmans-robin** [comment]
Hi Joshua, thanks for the quick reply! The GPU is not the problem, as I get the exact same result when I send it to my CPU instead. Reducing the number of workers does not have an effect either. Looking closer into the source code and using some well-placed print commands, I have found the issue appears in line 184 of utils.py: 

"subprocess.run(['/bin/bash', '-ic', mgl_command.format(pdb_path_tempdir1)], cwd=output_dir, check=True)"

At the start of a loop it runs fine, but when it starts processing a second pocket the process stops. I think the issue might be related to the workaround for MGLTools.

**Comment by poelmans-robin** [comment]
Update: I was able to resolve the issue by editing the mgl_command variable:

"mgl_command = 'source /home/biomol/miniconda3/bin/activate; conda activate deeplytough_mgltools2; python ' \
                  '$CONDA_PREFIX/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_receptor4.py ' \
                  '-r {} -U nphs_lps_waters -A hydrogens; **conda activate deeplytough**' "

After running the MGLTools script, the original deeplytough environment should be reactivated to ensure the loop keeps working
