### ISSUE TITLE
htmd.molecule.voxeldescriptors

### ISSUE THREAD

**Issue by byustudent** [BenevolentAI/DeeplyTough#3]
I'm having an issue with import htmd.molecule.voxeldescriptors in the msc/utils.py file. I've installed the newest version of htmd through conda, but it does not appear to have the voxeldescriptors module within it. I've gone through my miniconda files searching for it, but for whatever reason, it is not there. htmd.molecule.molecule is there, so I don't think I've installed htmd incorrectly. Is it possible a newer version of htmd exists that removed that or moved it somewhere else? Any help would be appreciated

**Comment by mys007** [comment]
Hi, indeed, there has been some refactoring in htmd, that's why froze the version to `htmd=1.13.10`. Can you confirm that when installing the dependencies as in https://github.com/BenevolentAI/DeeplyTough#code-setup, the problem goes away? Thanks!

**Comment by byustudent** [comment]
That would make sense. I thought I had followed those directions, but I guess I somehow missed them and installed the current version.


Only problem is, now when I run that code I get:
conda install -y -n deeplytough -c anaconda -c acellera -c psi4 biopython=1.72 htmd=1.13.10

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - biopython=1.72 -> python[version='>=3.8,<3.9.0a0']

Your python: python=3.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ca-certificates conflicts for:
python=3.6 -> openssl[version='>=1.1.1g,<1.1.2a'] -> ca-certificates
biopython=1.72 -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates

**Comment by mys007** [comment]
Hmm, that's weird... Are you trying it with new environments? Perhaps, I would suggest you try removing `deeplytough` and `deeplytough_mgltools` environments and rerun all the setup commands?
